# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 169282b48d29eb57d9f166453c64cab9e441b0ccc835a5b30ac58ff7ae25c6ffd2dc400713e2cd50ce4595ad19d4f27993697c06fbf7a113caf5aede6f634b1e

test:
  secret_key_base: cca16eabf233b8c0a1b4cf4030a3902abbc57eecbbf8b33ae279e84b17a4de1e1b60099426dcac050e2ef5428ede5b7ea52819e6c7b5b6aff5aa2e117f15eaf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
